### ISSUE TITLE
Core: Write EVM PairBridgeRegister contract

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/telos-token-bridge#8]
## Description

Will be the single source of truth for the bridge, meaning we will read it from Antelope to check registration there.
We keep Registration requests separate from the Pair array to keep the list consulted by bridge low.

_We use arrays instead of mappings because else we would need to know the mapping keys to iterate on Antelope side._

## Tasks

- [x] Registration requests
- [x] Registration approval for prods.evm
- [x] Registration Antelope signing
- [x] Token CRUD from prods.evm 
- [x] Full unit test coverage
- [x] Review once Antelope side is up
